[package]
name = "esp32-battery"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "esp32-battery"
harness = false

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
strip = true

[profile.dev]
debug = true
opt-level = "z"

[workspace]
exclude = ["logic"]

[features]
default = ["esp32c6", "lcd"]
esp32c3 = []
esp32c6 = []
lcd = ["mipidsi", "embedded-graphics"]
ina-fake = []
xy-fake = []

[dependencies]
esp32-battery-logic = { path = "logic" }
xy-modbus = { git = "https://github.com/xorza/xy-modbus", branch = "master", features = ["esp-idf-hal"] }
log = "*"
esp-idf-svc = "*"
esp-idf-hal = "*"
ina228 = "*"
embedded-hal = "*"
heapless = "*"
hmac = "*"
sha2 = { version = "*", default-features = false }
serde = { version = "*", default-features = false, features = ["derive"] }
serde-json-core = "*"
strum = { version = "*", default-features = false, features = ["derive"] }
mipidsi = { version = "*", optional = true }
embedded-graphics = { version = "*", optional = true }

[build-dependencies]
embuild = "*"
flate2 = "*"

[patch.crates-io]
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys.git", branch = "master" }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc.git", branch = "master" }
esp-idf-hal = { git = "https://github.com/xorza/esp-idf-hal.git", branch = "feat/i2c-driver" }

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/mdns", version = "*" }
