{
 "title": "ESP32 Battery Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Battery SOC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"soc\") |> last()"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"voltage\") |> last()"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"rssi\") |> last()"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"uptime\") |> last()"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"power_online\") |> last()"
    }
   ]
  },
  {
   "title": "Uptime %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"power_online\") |> mean() |> map(fn: (r) => ({r with _value: r._value * 100.0}))"
    }
   ]
  },
  {
   "title": "Max Charge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Ah" } },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"max_charge\") |> last()"
    }
   ]
  },
  {
   "title": "Read Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"read_failures\") |> last()"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"voltage\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"battery_current\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"battery\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"supply_current\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"battery_power\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"battery\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"supply_power\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Ah" } },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"charge\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "SOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"battery\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"soc\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}