[agent]
  interval = "1s"
  flush_interval = "1s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "battery"
  bucket = "battery"

[[inputs.http]]
  urls = ["http://${ESP32_HOST}/api"]
  method = "GET"
  timeout = "5s"
  data_format = "json_v2"

  [inputs.http.tags]
    device = "esp32-battery"

  [[inputs.http.json_v2]]
    measurement_name = "battery"

    [[inputs.http.json_v2.field]]
      path = "voltage"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "uptime"
      type = "int"
    [[inputs.http.json_v2.field]]
      path = "rssi"
      type = "int"
    [[inputs.http.json_v2.field]]
      path = "charge"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "max_charge"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "battery.soc"
      rename = "soc"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "battery.current"
      rename = "battery_current"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "battery.power"
      rename = "battery_power"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "ps.current"
      rename = "supply_current"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "ps.power"
      rename = "supply_power"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "power_online"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "read_err.0"
      rename = "read_failures"
      type = "int"
    [[inputs.http.json_v2.field]]
      path = "read_err.1"
      rename = "read_total"
      type = "int"
