[agent]
  interval = "1s"
  flush_interval = "1s"
  hostname = "battery-monitor"
  omit_hostname = false

[[outputs.health]]
  service_address = "http://:8080"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "battery"
  bucket = "battery"

[[inputs.http]]
  urls = ["https://${ESP32_HOST}/api"]
  method = "GET"
  timeout = "5s"
  insecure_skip_verify = true
  tagexclude = ["url"]
  data_format = "json_v2"

  [inputs.http.tags]
    device = "esp32-battery"

  [[inputs.http.json_v2]]
    measurement_name = "battery"

    [[inputs.http.json_v2.field]]
      path = "voltage"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "uptime"
      type = "int"
    [[inputs.http.json_v2.field]]
      path = "rssi"
      type = "int"
    [[inputs.http.json_v2.field]]
      path = "battery.soc"
      rename = "soc"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "battery.current"
      rename = "battery_current"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "battery.power"
      rename = "battery_power"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "ps.voltage"
      rename = "supply_voltage"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "ps.current"
      rename = "supply_current"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "ps.power"
      rename = "supply_power"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "power_online"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "heap.free"
      rename = "heap_free"
      type = "int"
    [[inputs.http.json_v2.field]]
      path = "heap.min_free"
      rename = "heap_min_free"
      type = "int"
